language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install:
  - composer config -g github-oauth.github.com $CI_USER_TOKEN

install:
  - composer install

script: phpunit
